-- ── Seed: Senate Class III Special Elections (2026) ────────
-- Class II (33 seats) are the regular cycle for 2026 — see 2026_elections.sql.
-- Class III special elections occur when a Class III senator vacates mid-term
-- (death, resignation, appointment, etc.). Add them here as they arise.
--
-- Class II states (regular 2026 cycle):
-- AL, AK, AR, CO, DE, GA, ID, IL, IA, KS, KY, LA, ME, MA,
-- MI, MN, MS, MT, NE, NH, NJ, NM, NC, OK, OR, RI, SC, SD,
-- TN, TX, VA, WV, WY
--
-- Class III special election template (uncomment and fill as needed):
-- INSERT INTO elections (state, office, district, senate_class, election_type, election_date)
-- VALUES ('XX', 'senate', NULL, 3, 'special', '2026-11-03')
-- ON CONFLICT DO NOTHING;
