-- ── Seed: All 50 states + DC ──────────────────────────────
INSERT INTO states (code, name, fips_code, house_seats, region)
VALUES
  ('AL', 'Alabama',         '01', 7,  'south'),
  ('AK', 'Alaska',          '02', 1,  'west'),
  ('AZ', 'Arizona',         '04', 9,  'west'),
  ('AR', 'Arkansas',        '05', 4,  'south'),
  ('CA', 'California',      '06', 52, 'west'),
  ('CO', 'Colorado',        '08', 8,  'west'),
  ('CT', 'Connecticut',     '09', 5,  'northeast'),
  ('DE', 'Delaware',        '10', 1,  'northeast'),
  ('FL', 'Florida',         '12', 28, 'south'),
  ('GA', 'Georgia',         '13', 14, 'south'),
  ('HI', 'Hawaii',          '15', 2,  'west'),
  ('ID', 'Idaho',           '16', 2,  'west'),
  ('IL', 'Illinois',        '17', 17, 'midwest'),
  ('IN', 'Indiana',         '18', 9,  'midwest'),
  ('IA', 'Iowa',            '19', 4,  'midwest'),
  ('KS', 'Kansas',          '20', 4,  'midwest'),
  ('KY', 'Kentucky',        '21', 6,  'south'),
  ('LA', 'Louisiana',       '22', 6,  'south'),
  ('ME', 'Maine',           '23', 2,  'northeast'),
  ('MD', 'Maryland',        '24', 8,  'northeast'),
  ('MA', 'Massachusetts',   '25', 9,  'northeast'),
  ('MI', 'Michigan',        '26', 13, 'midwest'),
  ('MN', 'Minnesota',       '27', 8,  'midwest'),
  ('MS', 'Mississippi',     '28', 4,  'south'),
  ('MO', 'Missouri',        '29', 8,  'midwest'),
  ('MT', 'Montana',         '30', 2,  'west'),
  ('NE', 'Nebraska',        '31', 3,  'midwest'),
  ('NV', 'Nevada',          '32', 4,  'west'),
  ('NH', 'New Hampshire',   '33', 2,  'northeast'),
  ('NJ', 'New Jersey',      '34', 12, 'northeast'),
  ('NM', 'New Mexico',      '35', 3,  'west'),
  ('NY', 'New York',        '36', 26, 'northeast'),
  ('NC', 'North Carolina',  '37', 14, 'south'),
  ('ND', 'North Dakota',    '38', 1,  'midwest'),
  ('OH', 'Ohio',            '39', 15, 'midwest'),
  ('OK', 'Oklahoma',        '40', 5,  'south'),
  ('OR', 'Oregon',          '41', 6,  'west'),
  ('PA', 'Pennsylvania',    '42', 17, 'northeast'),
  ('RI', 'Rhode Island',    '44', 2,  'northeast'),
  ('SC', 'South Carolina',  '45', 7,  'south'),
  ('SD', 'South Dakota',    '46', 1,  'midwest'),
  ('TN', 'Tennessee',       '47', 9,  'south'),
  ('TX', 'Texas',           '48', 38, 'south'),
  ('UT', 'Utah',            '49', 4,  'west'),
  ('VT', 'Vermont',         '50', 1,  'northeast'),
  ('VA', 'Virginia',        '51', 11, 'south'),
  ('WA', 'Washington',      '53', 10, 'west'),
  ('WV', 'West Virginia',   '54', 2,  'south'),
  ('WI', 'Wisconsin',       '55', 8,  'midwest'),
  ('WY', 'Wyoming',         '56', 1,  'west'),
  ('DC', 'District of Columbia', '11', 1, 'northeast')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  fips_code = EXCLUDED.fips_code,
  house_seats = EXCLUDED.house_seats;
